version: '3'
services:
  db:
    image: postgres
    volumes:
      - /tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: dev_password
    ports:
     - "5432:5432"
  web:
    image: python:3.6-slim
    working_dir: /app
    volumes:
      - ./hiss:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      PORT: 8000
      DATABASE_URL: postgres://postgres:dev_password@db:5432/hiss
    expose:
      - 8000
    command: bash -c "
      python3 -m pip install -r requirements.txt &&
      python3 manage.py runserver 0.0.0.0:8000"