name: Code Quality Checks

on: [push]

jobs:
  build:
    steps:
      - uses: lgeiger/black-action@v1.0.1
      - name: Compliant with Black formatting style
      - uses: cclauss/GitHub-Action-for-pylint@0.6.1
      - name: Passes Pylint checks