name: Code Quality Checks

on: [push]

jobs:
  black:
    name: 'Check compliance with Black formatting style'
    runs-on: ubuntu-latest
    steps:
      - uses: lgeiger/black-action@v1.0.1
  pylint:
    name: 'Check code health with Pylint'
    runs-on: ubuntu-latest
    steps:
      - uses: cclauss/GitHub-Action-for-pylint@0.6.1
